use_frameworks!

platform :ios, '12.1'

source 'https://github.com/CocoaPods/Specs.git'

target 'SwiftAirtable_Example' do
  pod 'SwiftAirtable', :path => '../'

end

target 'SwiftAirtable_Tests' do
	pod 'SwiftAirtable', :path => '../'
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
      end
    end
end
